name: .NET

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
    build:
        runs-on: windows-latest

        steps:
            - uses: actions/checkout@v2
            - name: Setup .NET
              uses: actions/setup-dotnet@v1
              with:
                dotnet-version: 6.0.x
            - name: Restore dependencies2
              run: dotnet restore
            - name: Build2
              run: dotnet build --no-restore
            - name: Test2
              run: dotnet test --no-build --verbosity normal
      
